#!/bin/bash

# Replace the following URL with a public GitHub repo URL
gitrepo=https://github.com/Azure-Samples/php-docs-hello-world
webappname=groundweb$RANDOM

# Create a resource group.
az group create --location westeurope --name groundweb

# Create an App Service plan in `FREE` tier.
az appservice plan create --name groundweb --resource-group groundweb --sku FREE

# Create a web app.
az webapp create --name groundweb --resource-group groundweb --plan groundweb

# Deploy code from a public GitHub repository. 
az webapp deployment source config --name groundweb --resource-group myResourceGroup --repo-url https://github.com/Portree-Kid/groundweb --branch master --manual-integration

# Copy the result of the following command into a browser to see the web app.
echo http://groundweb.azurewebsites.net